package com.interview;
import java.util.*;
public final class Questions {
 public record Q(String id,String role,String level,String topic,String prompt,List<String>terms,String reference) {public Map<String,Object>publicView(){return Map.of("id",id,"topic",topic,"prompt",prompt);}}
 public static final List<Q> ALL=new ArrayList<>();
 static void q(String id,String role,String level,String topic,String prompt,String terms,String reference){ALL.add(new Q(id,role,level,topic,prompt,List.of(terms.split(";")),reference));}
 static{
 q("w1","Web developer","Beginner","HTML","Why would you choose semantic HTML over a page made entirely of div elements?","meaning;accessibility;navigation","Semantic elements describe the purpose of content. Use nav for navigation, main for the main content and a real button for an action. This helps people and assistive technology understand the page.");
 q("w2","Web developer","Beginner","Validation","Why must a server validate input even when the browser already validates the form?","server;bypass;invalid","Browser checks provide quick feedback but clients can bypass them. The server must enforce business rules before accepting or storing data. Give an example such as rejecting a negative quantity.");
 q("w3","Web developer","Beginner","CSS","How would you make a two-column page work well on a phone?","grid;media;column","Use flexible Grid or Flexbox, relative sizing and a breakpoint that stacks columns when space is limited. Check text size, keyboard access and horizontal overflow.");
 q("w4","Web developer","Beginner","HTTP","What is the difference between GET and POST in a web application?","retrieve;body;change","GET retrieves a representation and should not change server state. POST submits content for processing, often creating a resource. Both need appropriate authentication and transport security.");
 q("w5","Web developer","Beginner","JavaScript","What does async/await help you do when loading data from an API?","promise;await;error","An async function returns a promise. Await lets you work with its result without blocking the main thread while waiting. Handle HTTP failures separately from network failures and restore loading state in finally.");
 q("w6","Web developer","Intermediate","Security","How do you prevent one user from accessing another user's interview by changing its URL?","owner;server;authorization","Authenticate the requester and check resource ownership on every server-side read and write. An unpredictable ID is helpful but is not a substitute for authorization.");
 q("w7","Web developer","Intermediate","Reliability","A user clicks Submit twice. How can your backend avoid storing two answers?","idempotency;unique;transaction","Use a client submission identifier with a database uniqueness constraint. The same key and content should return the original result. Conflicting content should produce a conflict. Apply state changes atomically.");
 q("w8","Web developer","Intermediate","Browser","Explain how cross-site scripting can occur in a feedback page and how to prevent it.","textcontent;escape;untrusted","Treat user and model output as untrusted. Insert plain feedback with textContent or a framework's safe text rendering. Sanitize any deliberately allowed HTML and use a restrictive content security policy.");
 q("w9","Web developer","Intermediate","Database","When would you add an index to a table of interview sessions?","query;index;write","Examine frequent filters and sorting such as user_id with created_at. An index can reduce lookup work but adds storage and write overhead. Check an execution plan against representative data.");
 q("w10","Web developer","Intermediate","Architecture","What should happen if an AI evaluator times out after an answer has been saved?","saved;retry;status","Keep the answer persisted and return a clear evaluation status. Allow a bounded retry with duplicate protection. Do not turn an infrastructure failure into a low score.");
 q("j1","Java developer","Beginner","OOP","How is an interface different from a class in Java?","contract;implements;instance","An interface defines a contract that classes implement. A class holds implementation and instance state. Explain that interfaces can also define default and static methods.");
 q("j2","Java developer","Beginner","Collections","When would you choose a HashMap rather than an ArrayList?","key;lookup;list","A HashMap associates keys with values and supports average constant-time key lookup. An ArrayList stores an ordered sequence with indexed access. Choose based on the access pattern.");
 q("j3","Java developer","Beginner","Exceptions","Why is try-with-resources useful when working with a database?","close;resource;exception","Try-with-resources closes AutoCloseable resources even when an exception occurs. Use it for connections, statements and result sets to prevent resource leaks.");
 q("j4","Java developer","Beginner","OOP","Explain method overriding with a simple example.","subclass;method;runtime","A subclass provides an implementation of an inherited overridable method with a compatible signature. A reference to the parent type can dispatch to the subclass implementation at runtime.");
 q("j5","Java developer","Beginner","Strings","What is the difference between == and equals when comparing strings?","reference;content;equals","For objects, == compares references. String.equals compares character content. Interning can make some references equal, so it should not be relied on for content comparisons.");
 q("j6","Java developer","Intermediate","Servlets","Why should request-specific data not be stored in a servlet instance field?","thread;shared;request","A servlet instance can process concurrent requests. Shared mutable request data can leak across users or race. Keep it in local variables or correctly scoped objects.");
 q("j7","Java developer","Intermediate","JDBC","How does a PreparedStatement help prevent SQL injection?","parameter;sql;data","Bind user values as parameters rather than concatenating them into SQL. The driver treats values as data. Identifiers and ordering clauses still require allowlists.");
 q("j8","Java developer","Intermediate","Concurrency","What problem does synchronized solve, and what are its limits?","lock;thread;process","Synchronized provides mutual exclusion and visibility around a shared monitor within one JVM. It does not coordinate separate application processes. Long critical sections reduce concurrency.");
 q("j9","Java developer","Intermediate","Transactions","Why should related database changes happen in a transaction?","atomic;rollback;commit","A transaction groups changes so they commit or roll back together. This avoids partial updates. Isolation and constraints still matter for concurrent access.");
 q("j10","Java developer","Intermediate","Errors","How should an API handle an unexpected exception without exposing private information?","log;status;message","Return a generic error with a useful status and request identifier. Log enough detail on the server to diagnose it without logging passwords or complete private answers.");
 }
 public static Q get(String id){return ALL.stream().filter(q->q.id.equals(id)).findFirst().orElseThrow(()->new IllegalArgumentException("Question unavailable"));}
}
