'use strict';
const $=id=>document.getElementById(id);let user=null,session=null,register=false,questionIndex=0,busy=false,recognition=null,recording=false,submission=null;
const sections=['auth','setup','interview','review','history','summary','loading'];
function show(id){stopVoice();sections.forEach(x=>$(x).hidden=x!==id);$('practiceNav').classList.toggle('active',['setup','interview','review','auth'].includes(id));$('historyNav').classList.toggle('active',['history','summary'].includes(id));window.scrollTo({top:0,behavior:'auto'});}
function toast(message){$('notice').textContent=message;}
function el(tag,text,className){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(className)n.className=className;return n;}
async function api(path,body){const response=await fetch('api'+path,{method:body===undefined?'GET':'POST',credentials:'same-origin',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await response.json();}catch{throw Error('The server returned an unreadable response. Please try again.');}if(!response.ok){if(response.status===401){user=null;setUser();show('auth');}throw Error(data.error||'Request failed');}return data;}
function setUser(){ $('userName').textContent=user?.name||'';$('logout').hidden=!user;const option=$('mode').options[1];option.disabled=!user?.aiAvailable;option.textContent=user?.aiAvailable?'AI-assisted feedback':'AI-assisted feedback (not configured)';$('greeting').textContent=user?'Ready for your next round, '+user.name.split(' ')[0]+'?':'Ready for your next round?';}
function draftKey(){return session&&user?'draft:'+user.email+':'+session.id+':'+questionIndex:null;}
function saveDraft(){const key=draftKey();if(key){try{sessionStorage.setItem(key,$('answer').value);}catch{toast('Draft storage is unavailable. Submit your answer before leaving.');}}}
function stopVoice(){if(recognition&&recording)recognition.stop();recording=false;if($('voice'))$('voice').textContent='Use microphone';}
async function history(){if(busy)return;if(!user){show('auth');return;}show('loading');try{const list=await api('/sessions');const root=$('historyList');root.replaceChildren();if(!list.length){const empty=el('div',undefined,'empty');empty.append(el('h2','Your first session is waiting.'),el('p','Choose a role and give five questions a try.'));root.append(empty);}for(const s of list){const row=el('article',undefined,'history-item'),left=el('div');left.append(el('h2',s.role),el('p',s.level+' · '+new Date(s.created).toLocaleString()),el('span',s.answered+' of '+s.total+' answers saved'+(s.status==='COMPLETED'?' · Complete':' · In progress'),'status'));const button=el('button',s.status==='COMPLETED'?'Review session':'Resume session','secondary');button.addEventListener('click',()=>openSession(s.id));row.append(left,button);root.append(row);}show('history');}catch(e){toast(e.message);if(user)show('setup');}}
async function openSession(id){try{session=await api('/sessions/'+id);submission=null;if(session.answers.length===session.questions.length)summary();else if(session.answers.length&&session.answers.at(-1).status!=='READY')review(session.answers.length-1);else question();}catch(e){toast(e.message);}}
function question(){questionIndex=session.answers.length;const q=session.questions[questionIndex];if(!q){summary();return;}show('interview');$('sessionMeta').textContent=session.role.toUpperCase()+' / '+session.level.toUpperCase();$('questionCount').textContent='Question '+(questionIndex+1)+' of '+session.questions.length;$('topic').textContent=q.topic;$('progressFill').style.width=(questionIndex/session.questions.length*100)+'%';$('questionText').textContent=q.prompt;try{$('answer').value=sessionStorage.getItem(draftKey())||'';}catch{$('answer').value='';}count();$('answerError').textContent='';$('questionList').replaceChildren(...session.questions.map((q,i)=>el('li',(i<questionIndex?'✓ ':String(i+1).padStart(2,'0')+'  ')+q.topic,i===questionIndex?'current':'')));}
function feedback(answer,index){const wrap=el('div',undefined,'feedback-grid'),original=el('article',undefined,'card'),result=el('article',undefined,'card');original.append(el('p','QUESTION '+(index+1),'eyebrow'),el('h2',session.questions[index].prompt,'question-heading'),el('h3','Your answer'),el('p',answer.answer));if(answer.status==='READY'){const f=answer.feedback;result.append(el('p',f.mode.toUpperCase(),'eyebrow'));for(const [key,label] of [['strength','What you covered'],['gap','What to review'],['next','Your next step']])result.append(el('h3',label),el('p',f[key]));const ref=el('div',undefined,'reference');ref.append(el('h3','Reference explanation'),el('p',f.reference));result.append(ref,el('p',f.notice,'small'));}else{result.append(el('h2','Your answer is saved.'),el('p','Feedback is unavailable. Retry it, or continue your interview.'));const retry=el('button','Retry feedback','secondary next');retry.disabled=Number(answer.retries)>=3;retry.addEventListener('click',async()=>{retry.disabled=true;retry.textContent='Evaluating…';try{session=await api('/sessions/'+session.id+'/retry',{key:answer.key});if(!$('summary').hidden)summary();else review(index);}catch(e){toast(e.message);retry.disabled=false;retry.textContent='Retry feedback';}});result.append(retry);}wrap.append(original,result);return wrap;}
function review(index){show('review');$('reviewMeta').textContent='QUESTION '+(index+1)+' REVIEW';$('feedbackContent').replaceChildren(feedback(session.answers[index],index));$('next').textContent=session.answers.length===session.questions.length?'View session summary':'Next question';}
function summary(){show('summary');$('summaryMeta').textContent=session.role+' · '+session.level+' · '+session.answers.length+' answers saved';$('summaryContent').replaceChildren(...session.answers.map((a,i)=>{const d=el('details');d.open=i===0;d.append(el('summary',(i+1)+'. '+session.questions[i].topic+' — '+(a.status==='READY'?'Feedback ready':'Feedback unavailable')),feedback(a,i));return d;}));}
function count(){$('charCount').textContent=$('answer').value.length.toLocaleString()+' / 6,000';}
$('switchAuth').onclick=()=>{register=!register;$('nameField').hidden=!register;$('name').required=register;$('authTitle').textContent=register?'Create your practice space':'Continue your practice';$('authKicker').textContent=register?'A SMALL STEP FORWARD':'WELCOME BACK';$('authSubmit').textContent=register?'Create account':'Sign in';$('switchAuth').textContent=register?'Already registered? Sign in':'New here? Create an account';$('password').autocomplete=register?'new-password':'current-password';$('authError').textContent='';};
$('authForm').onsubmit=async e=>{e.preventDefault();$('authSubmit').disabled=true;$('authError').textContent='';try{await api('/auth/'+(register?'register':'login'),{name:$('name').value,email:$('email').value,password:$('password').value});$('password').value='';user=await api('/me');setUser();toast('');show('setup');}catch(err){$('authError').textContent=err.message;}finally{$('authSubmit').disabled=false;}};
$('logout').onclick=async()=>{if(busy)return;try{await api('/auth/logout',{});for(const k of Object.keys(sessionStorage))if(k.startsWith('draft:'))sessionStorage.removeItem(k);user=null;session=null;setUser();show('auth');toast('You have signed out.');}catch(e){toast(e.message);}};
$('mode').onchange=()=>{$('modeHelp').textContent=$('mode').value==='ai'?'Your answer and the question will be sent to the configured AI provider. Feedback can be wrong; review it alongside the reference.':'No API key needed. Compare your answer with reviewed reference points. Term matching does not judge correctness.';};
$('setupForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{session=await api('/sessions',{role:$('role').value,level:document.querySelector('[name=level]:checked').value,mode:$('mode').value});submission=null;toast('');question();}catch(err){toast(err.message);}finally{btn.disabled=false;}};
$('answer').oninput=()=>{count();saveDraft();submission=null;};
$('answerForm').onsubmit=async e=>{e.preventDefault();if(busy)return;stopVoice();const answer=$('answer').value.trim();if(answer.length<10){$('answerError').textContent='Please write at least 10 characters.';return;}busy=true;$('submitAnswer').disabled=true;$('leave').disabled=true;$('answer').readOnly=true;$('answerError').textContent='';$('submitAnswer').textContent='Saving and preparing feedback…';saveDraft();const key=draftKey();submission??={key:crypto.randomUUID(),questionId:session.questions[questionIndex].id,answer};try{session=await api('/sessions/'+session.id+'/answers',submission);sessionStorage.removeItem(key);submission=null;review(questionIndex);}catch(err){$('answerError').textContent=err.message;}finally{busy=false;$('submitAnswer').disabled=false;$('leave').disabled=false;$('answer').readOnly=false;$('submitAnswer').textContent='Submit answer';}};
$('next').onclick=()=>question();$('leave').onclick=()=>{saveDraft();history();};$('reviewLeave').onclick=history;$('historyNav').onclick=()=>{if(!$('interview').hidden)saveDraft();history();};$('practiceNav').onclick=()=>{if(busy)return;if(!$('interview').hidden)saveDraft();show(user?'setup':'auth');};$('newSession').onclick=$('again').onclick=()=>show('setup');
$('download').onclick=()=>{const data={role:session.role,level:session.level,created:session.created,answers:session.answers.map((a,i)=>({question:session.questions[i].prompt,answer:a.answer,status:a.status,feedback:a.feedback||null}))};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='interview-session-'+session.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(Speech){$('voice').hidden=false;recognition=new Speech();recognition.lang='en-IN';recognition.continuous=true;recognition.interimResults=false;recognition.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)$('answer').value=($('answer').value+' '+e.results[i][0].transcript).slice(0,6000);count();saveDraft();submission=null;};recognition.onerror=e=>{$('voiceStatus').textContent='Microphone unavailable ('+e.error+'). You can keep typing.';stopVoice();};recognition.onend=()=>{recording=false;$('voice').textContent='Use microphone';};$('voice').onclick=()=>{if(busy)return;if(recording){stopVoice();return;}try{recognition.start();recording=true;$('voice').textContent='Stop microphone';$('voiceStatus').textContent='Listening. Review the transcript before submitting. Your browser may use a remote speech service.';}catch{$('voiceStatus').textContent='Voice input is unavailable. Please type your answer.';}};}
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}else if(!$('interview').hidden)saveDraft();});
(async()=>{show('loading');try{user=await api('/me');setUser();show('setup');}catch{show('auth');}})();
